# Generated by Django 4.2.3 on 2023-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_demomodel_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okmail', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=70)),
                ('comment', models.CharField(max_length=70)),
                ('num', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
